export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CART_NUMBER = "SET_CART_NUMBER"
export const UPDATE_CART = "UPDATE_CART"